# implement try exception
# take in


print("a^2+b^2=c^2")
print("---------------------")
